backend:
  name: git-gateway
  accept_roles:
    - admin
  branch: master

media_folder: "assets/img/uploads"
  
collections:

  - label: "Noticias"
    name: "posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Upload Video", name: "video_upload", widget: "boolean", default: false}
      - {label: "Video", name: "video", widget: "file", required: false}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - label: "Categoria"
        name: "category"
        widget: "select"
        options: ["noticias", "criminalidade", "desporto", "tecnologias", "biffs"]
      - label: "Tag"
        name: "tag"
        widget: "select"
        options: ["mozambique", "mundo", "uefa"]
      - {label: "Layout", name: "layout", default: "post", widget: "hidden"}
      - {label: "Area de Texto", name: "body", widget: "markdown"}